spring:
  application:
    name: eureka-server
eureka:
  custom:
    node1-port: 8762
    node2-port: 8763
    node3-port: 8764
  instance:
    prefer-ip-address: true
    appname: eureka.node2
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.cloud.client.ip-address}:${eureka.custom.node1-port}/eureka,http://${spring.cloud.client.ip-address}:${eureka.custom.node2-port}/eureka,http://${spring.cloud.client.ip-address}:${eureka.custom.node3-port}/eureka
  server:
    eviction-interval-timer-in-ms: 10000
server:
  port: ${eureka.custom.node2-port}